### ISSUE TITLE
Create dashboard admin

### ISSUE THREAD

**Issue by dhimasanb** [dhimasanb/villa-lombok#1]

**Comment by aldaaladawiyah** [comment]
jadi di dashboardnya ada form untuk tambah data, hapus, update buat si admin. dan data yg udah diupload akan tampil di menu book now. buat dashboard untuk artikel di special events juga. semua artikel yang diupload di dashboard akan  muncul di menu special events. Untuk fieldnya sama persis kaya di field database.

**Comment by dhimasanb** [comment]
0d11591

**Comment by dhimasanb** [comment]
Final update : ded8d2c
